version: "3.8"

volumes:
  postgres:

services:
  snippet_box:
    build: .
    restart: always
    ports:
    - 4000:4000
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: snippetbox
    volumes:
    - ./postgres:/var/lib/postgresql/data
    - ./postgresql/:/docker-entrypoint-initdb.d/

